### ISSUE TITLE
Not able to link to the login dn register page-using q2a 1.8.4

### ISSUE THREAD

**Issue by vraghavans** [q2apro/q2a-chat-extended#2]
if the user is trying to enter the chat screen from a link and is not logged in,there is a error mesage to log in or register,but the link is not work and there is a an error Page not found.

Please help

**Comment by q2apro** [comment]
The links are correct:

> $qa_content['error'] = 'Bitte <a href="'.qa_path('login').'?to=chat">einloggen</a> oder <a href="'.qa_path('register').'?to=chat">registrieren</a>, um den Chat benutzen zu können.';

https://github.com/q2apro/q2a-chat-extended/blob/master/qa-chat.php#L253

**Comment by vraghavans** [comment]
Thanks for the quick reply,greatly appreciate!,i have just changed the language of the text in the above code to English,will it make a differnce,can you pls guide me,why the error please?
thanks!
Rgds
Vijay

**Comment by vraghavans** [comment]
![image](https://user-images.githubusercontent.com/65802024/90345807-85c50880-e041-11ea-8d37-79fccd9c8483.png)
when i click log in,this is what i get

![image](https://user-images.githubusercontent.com/65802024/90345820-9f665000-e041-11ea-9804-a77614f8a82d.png)

**Comment by vraghavans** [comment]
can anyone please help me on this please
